#!/usr/bin/env python3

"""
Get list of files where OTRS approval is missing
"""

import os

from mwclient import Site

import otrs


def main():
    """
    Main function to get list of pages needing OTRS approval
    """

    site = Site("commons.wikimedia.org")
    category = site.categories["Audio recordings by Waithera Were"]
    for page in category:
        page_name = os.path.basename(page.imageinfo["descriptionurl"])
        otrs_id = otrs.get_otrs(page.text())
        if not otrs_id:
            if otrs.is_otrs_pending(page.text()):
                print(page_name)
            else:
                print(f"Can't establish OTRS status for page {page_name}")


if __name__ == "__main__":
    main()
